services:
  apigateway:
    container_name: "apigateway"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
    networks:
      - universe-network
  

networks:
  universe-network:
    external: true
