# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  taxcalculation:
    image: taxcalculation
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6002:6002
    networks:
      - universe-network

networks:
  universe-network:
    external: true