services:
  testtaxcalculation:
    container_name: "taxcalculation"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5004:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
    networks:
      - universe-network

networks:
  universe-network:
    external: true