services:
  coursesearch:
    container_name: "coursesearch"
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "5003:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_PATH=/app/data/courses.db
    networks:
      - universe-network

networks:
  universe-network:
    external: true