services:
  web:
    container_name: "vaccination_service"
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
    networks:
      - universe-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - universe-network

volumes:
  db_data:

networks:
  universe-network:
    external: true
